### ISSUE TITLE
Single Sermon Page - Fatal error: Uncaught Error: Call to undefined function is_plugin_active()

### ISSUE THREAD

**Issue by hermify** [WP-for-Church/Sermon-Manager#289]
Got error on single page: 
`Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-content/plugins/sermon-manager-for-wordpress/views/partials/content-sermon-single.php:109 Stack trace: #0 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-includes/template.php(732): require() #1 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-content/plugins/sermon-manager-for-wordpress/includes/sm-template-functions.php(715): load_template('/var/www/vhosts...', false) #2 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-content/plugins/sermon-manager-for-wordpress/includes/sm-template-functions.php(480): wpfc_get_partial('content-sermon-...') #3 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-content/plugins/sermon-manager-for-wordpress/views/single-wpfc_sermon.php(21): wpfc_sermon_single_v2() #4 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-includes/template-loader.php(106): include('/var/www/vhosts...') #5 /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-blog-header.php(19): require_once('/var/www/vhosts...') in /var/www/vhosts/fcg-guetersloh.de/httpdocs/wp-content/plugins/sermon-manager-for-wordpress/views/partials/content-sermon-single.php on line 109`

Single Page is broken: 
https://fcggt.de/predigt/geistesgaben-wort-der-weisssagung/

**### Platform**
**Sermon Manager Version: 2.16.7
**WordPress Version: 5.6.2
**PHP Version: 7.4

### Any Additional Info

Solution described in here: https://wordpress.stackexchange.com/questions/9345/is-plugin-active-function-doesnt-exist

**Comment by hermify** [comment]
I temporary added for myself:
```
if( !function_exists('is_plugin_active') || is_plugin_active( 'elementor/elementor.php' ) ) {
	the_content();
}else{

```

**Comment by DLBerger** [comment]
Your logic is wrong.  It should be:

`if( function_exists('is_plugin_active') && is_plugin_active( 'elementor/elementor.php' ) ) {
	the_content();
}else{`
